@ stub ?<Dispose>@Exception@Platform@@UE$AAAXXZ
@ stub ?<Dispose>@String@Platform@@UE$AAAXXZ
@ stub ?<Dispose>@Type@Platform@@UE$AAAXXZ
@ stub ??0AccessDeniedException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0AccessDeniedException@Platform@@QE$AAA@XZ
@ stub ??0Attribute@Metadata@Platform@@QE$AAA@XZ
@ stub ??0Boolean@Platform@@QEAA@_N@Z
@ stub ??0COMException@Platform@@QE$AAA@H@Z
@ stub ??0COMException@Platform@@QE$AAA@HPE$AAVString@1@@Z
@ stub ??0ChangedStateException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0ChangedStateException@Platform@@QE$AAA@XZ
@ stub ??0ClassNotRegisteredException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0ClassNotRegisteredException@Platform@@QE$AAA@XZ
@ stub ??0Delegate@Platform@@QE$AAA@XZ
@ stub ??0DisconnectedException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0DisconnectedException@Platform@@QE$AAA@XZ
@ stub ??0Enum@Platform@@QE$AAA@XZ
@ stub ??0Exception@Platform@@QE$AAA@H@Z
@ stub ??0Exception@Platform@@QE$AAA@HPE$AAVString@1@@Z
@ stub ??0FailureException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0FailureException@Platform@@QE$AAA@XZ
@ stub ??0GridLength@Xaml@UI@Windows@@QEAA@NW4GridUnitType@123@@Z
@ stub ??0IntPtr@Platform@@QEAA@H@Z
@ stub ??0IntPtr@Platform@@QEAA@PEAX@Z
@ stub ??0InvalidArgumentException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0InvalidArgumentException@Platform@@QE$AAA@XZ
@ stub ??0InvalidCastException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0InvalidCastException@Platform@@QE$AAA@XZ
@ stub ??0MTAThreadAttribute@Platform@@QE$AAA@XZ
@ stub ??0NotImplementedException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0NotImplementedException@Platform@@QE$AAA@XZ
@ stub ??0NullReferenceException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0NullReferenceException@Platform@@QE$AAA@XZ
@ stub ??0Object@Platform@@QE$AAA@XZ
@ stub ??0ObjectDisposedException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0ObjectDisposedException@Platform@@QE$AAA@XZ
@ stub ??0OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@QE$AAA@XZ
@ stub ??0OperationCanceledException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0OperationCanceledException@Platform@@QE$AAA@XZ
@ stub ??0OutOfBoundsException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0OutOfBoundsException@Platform@@QE$AAA@XZ
@ stub ??0OutOfMemoryException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0OutOfMemoryException@Platform@@QE$AAA@XZ
@ stub ??0Rect@Foundation@Windows@@QEAA@VPoint@12@0@Z
@ stub ??0Rect@Foundation@Windows@@QEAA@VPoint@12@VSize@12@@Z
@ stub ??0RepeatBehavior@Animation@Media@Xaml@UI@Windows@@QEAA@N@Z
@ stub ??0STAThreadAttribute@Platform@@QE$AAA@XZ
@ stub ??0SizeT@Platform@@QEAA@H@Z
@ stub ??0SizeT@Platform@@QEAA@PEAX@Z
@ stub ??0Type@Platform@@QE$AAA@PE$AAVObject@1@@Z
@ stub ??0Type@Platform@@QE$AAA@VIntPtr@1@@Z
@ stub ??0Type@Platform@@QE$AAA@VTypeName@Interop@Xaml@UI@Windows@@@Z
@ stub ??0ValueType@Platform@@QE$AAA@XZ
@ stub ??0WrongThreadException@Platform@@QE$AAA@PE$AAVString@1@@Z
@ stub ??0WrongThreadException@Platform@@QE$AAA@XZ
@ stub ??0char16@default@@QEAA@_W@Z
@ stub ??0float32@default@@QEAA@M@Z
@ stub ??0float64@default@@QEAA@N@Z
@ stub ??0int16@default@@QEAA@F@Z
@ stub ??0int32@default@@QEAA@H@Z
@ stub ??0int64@default@@QEAA@_J@Z
@ stub ??0int8@default@@QEAA@C@Z
@ stub ??0uint16@default@@QEAA@G@Z
@ stub ??0uint32@default@@QEAA@I@Z
@ stub ??0uint64@default@@QEAA@_K@Z
@ stub ??0uint8@default@@QEAA@E@Z
@ stub ??BIntPtr@Platform@@SA?AV01@H@Z
@ stub ??BIntPtr@Platform@@SA?AV01@PEAX@Z
@ stub ??BIntPtr@Platform@@SAPEAXV01@@Z
@ stub ??BType@Platform@@SA?AVTypeName@Interop@Xaml@UI@Windows@@PE$AAV01@@Z
@ stub ??BType@Platform@@SAPE$AAV01@VTypeName@Interop@Xaml@UI@Windows@@@Z
@ stub ??DMatrix3D@Media3D@Media@Xaml@UI@Windows@@SA?AV012345@V012345@0@Z
@ stub ??GDuration@Xaml@UI@Windows@@SA?AV0123@V0123@0@Z
@ stub ??HDuration@Xaml@UI@Windows@@SA?AV0123@V0123@0@Z
@ stub ??MDuration@Xaml@UI@Windows@@SA_NV0123@0@Z
@ stub ??NDuration@Xaml@UI@Windows@@SA_NV0123@0@Z
@ stub ??ODuration@Xaml@UI@Windows@@SA_NV0123@0@Z
@ stub ??PDuration@Xaml@UI@Windows@@SA_NV0123@0@Z
@ stub ?AlignedAllocate@Heap@Details@Platform@@SAPEAX_K00@Z
@ stub ?AlignedAllocate@Heap@Details@Platform@@SAPEAX_K0@Z
@ stub ?AlignedAllocateException@Heap@Details@Platform@@SAPEAX_K00@Z
@ stub ?AlignedAllocateException@Heap@Details@Platform@@SAPEAX_K0@Z
@ stub ?AlignedFree@Heap@Details@Platform@@SAXPEAX@Z
@ stub ?AlignedFreeException@Heap@Details@Platform@@SAXPEAX@Z
@ stub ?Allocate@Heap@Details@Platform@@SAPEAX_K0@Z
@ stub ?Allocate@Heap@Details@Platform@@SAPEAX_K@Z
@ stub ?AllocateException@Heap@Details@Platform@@SAPEAX_K0@Z
@ stub ?AllocateException@Heap@Details@Platform@@SAPEAX_K@Z
@ stub ?Compare@Duration@Xaml@UI@Windows@@SAHV1234@0@Z
@ stub ?Contains@Rect@Foundation@Windows@@QEAA_NVPoint@23@@Z
@ stub ?CreateException@Exception@Platform@@SAPE$AAV12@H@Z
@ stub ?CreateException@Exception@Platform@@SAPE$AAV12@HPE$AAVString@2@@Z
@ stub ?CreateValue@Details@Platform@@YAPE$AAVObject@2@W4TypeCode@2@PEBX@Z
@ stub ?EnableFactoryCache@@YAXXZ
@ stub ?EnumerateAllocatedObjects@Heap@Details@Platform@@SAXPE$AAVHeapEntryHandler@23@@Z
@ stub ?Equals@Attribute@Metadata@Platform@@QE$AAA_NPE$AAVObject@3@@Z
@ stub ?Equals@Boolean@Platform@@QEAA_NPE$AAVObject@2@@Z
@ stub ?Equals@Delegate@Platform@@QE$AAA_NPE$AAVObject@2@@Z
@ stub ?Equals@Enum@Platform@@QE$AAA_NPE$AAVObject@2@@Z
@ stub ?Equals@Exception@Platform@@UE$AAA_NPE$AAVObject@2@@Z
@ stub ?Equals@MTAThreadAttribute@Platform@@QE$AAA_NPE$AAVObject@2@@Z
@ stub ?Equals@Object@Platform@@QE$AAA_NPE$AAV12@@Z
@ stub ?Equals@OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@QE$AAA_NPE$AAVObject@4@@Z
@ stub ?Equals@STAThreadAttribute@Platform@@QE$AAA_NPE$AAVObject@2@@Z
@ stub ?Equals@Type@Platform@@UE$AAA_NPE$AAVObject@2@@Z
@ stub ?Equals@ValueType@Platform@@QE$AAA_NPE$AAVObject@2@@Z
@ stub ?Equals@char16@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@float32@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@float64@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@int16@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@int32@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@int64@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@int8@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@uint16@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@uint32@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@uint64@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?Equals@uint8@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub ?EventSourceAdd@Details@Platform@@YA?AVEventRegistrationToken@Foundation@Windows@@PEAPEAXPEAUEventLock@12@PE$AAVDelegate@2@@Z
@ stub ?EventSourceGetTargetArray@Details@Platform@@YAPEAXPEAXPEAUEventLock@12@@Z
@ stub ?EventSourceGetTargetArrayEvent@Details@Platform@@YAPEAXPEAXIPEBXPEA_J@Z
@ stub ?EventSourceGetTargetArraySize@Details@Platform@@YAIPEAX@Z
@ stub ?EventSourceInitialize@Details@Platform@@YAXPEAPEAX@Z
@ stub ?EventSourceRemove@Details@Platform@@YAXPEAPEAXPEAUEventLock@12@VEventRegistrationToken@Foundation@Windows@@@Z
@ stub ?EventSourceUninitialize@Details@Platform@@YAXPEAPEAX@Z
@ stub ?FlushFactoryCache@@YAXXZ
@ stub ?Free@Heap@Details@Platform@@SAXPEAX@Z
@ stub ?FreeException@Heap@Details@Platform@@SAXPEAX@Z
@ stub ?GetActivationFactory@Details@Platform@@YAJPEAVModuleBase@1WRL@Microsoft@@PEAUHSTRING__@@PEAPEAUIActivationFactory@@@Z
@ stub ?GetActivationFactoryByPCWSTR@@YAJPEAXAEAVGuid@Platform@@PEAPEAX@Z
@ stub ?GetCmdArguments@Details@Platform@@YAPEAPEA_WPEAH@Z
@ stub ?GetHashCode@Attribute@Metadata@Platform@@QE$AAAHXZ
@ stub ?GetHashCode@Boolean@Platform@@QEAAHXZ
@ stub ?GetHashCode@Delegate@Platform@@QE$AAAHXZ
@ stub ?GetHashCode@Enum@Platform@@QE$AAAHXZ
@ stub ?GetHashCode@Exception@Platform@@UE$AAAHXZ
@ stub ?GetHashCode@Guid@Platform@@QEAAHXZ
@ stub ?GetHashCode@MTAThreadAttribute@Platform@@QE$AAAHXZ
@ stub ?GetHashCode@Object@Platform@@QE$AAAHXZ
@ stub ?GetHashCode@OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@QE$AAAHXZ
@ stub ?GetHashCode@STAThreadAttribute@Platform@@QE$AAAHXZ
@ stub ?GetHashCode@Type@Platform@@UE$AAAHXZ
@ stub ?GetHashCode@ValueType@Platform@@QE$AAAHXZ
@ stub ?GetHashCode@char16@default@@QEAAHXZ
@ stub ?GetHashCode@float32@default@@QEAAHXZ
@ stub ?GetHashCode@float64@default@@QEAAHXZ
@ stub ?GetHashCode@int16@default@@QEAAHXZ
@ stub ?GetHashCode@int32@default@@QEAAHXZ
@ stub ?GetHashCode@int64@default@@QEAAHXZ
@ stub ?GetHashCode@int8@default@@QEAAHXZ
@ stub ?GetHashCode@uint16@default@@QEAAHXZ
@ stub ?GetHashCode@uint32@default@@QEAAHXZ
@ stub ?GetHashCode@uint64@default@@QEAAHXZ
@ stub ?GetHashCode@uint8@default@@QEAAHXZ
@ stub ?GetIBoxArrayVtable@Details@Platform@@YAPEAXPEAX@Z
@ stub ?GetIBoxVtable@Details@Platform@@YAPEAXPEAX@Z
@ stub ?GetIidsFn@@YAJHPEAKPEBU__s_GUID@@PEAPEAVGuid@Platform@@@Z
@ stub ?GetObjectContext@Details@Platform@@YAPEAUIUnknown@@XZ
@ stub ?GetProxyImpl@Details@Platform@@YAJPEAUIUnknown@@AEBU_GUID@@0PEAPEAU3@@Z
@ stub ?GetType@Boolean@Platform@@QEAAPE$AAVType@2@XZ
@ stub ?GetType@Guid@Platform@@QEAAPE$AAVType@2@XZ
@ stub ?GetType@Object@Platform@@QE$AAAPE$AAVType@2@XZ
@ stub ?GetType@char16@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@float32@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@float64@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@int16@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@int32@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@int64@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@int8@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@uint16@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@uint32@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@uint64@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetType@uint8@default@@QEAAPE$AAVType@Platform@@XZ
@ stub ?GetTypeCode@Type@Platform@@SA?AW4TypeCode@2@PE$AAV12@@Z
@ stub ?GetWeakReference@Details@Platform@@YAPEAU__abi_IUnknown@@QE$ADVObject@2@@Z
@ stub ?InitControlBlock@ControlBlock@Details@Platform@@AEAAXPEAX_N11@Z
@ stdcall ?InitializeData@Details@Platform@@YAJH@Z(long) wincorlib.?InitializeData@Details@Platform@@YAJH@Z
@ stub ?Intersect@Rect@Foundation@Windows@@QEAAXV123@@Z
@ stub ?IntersectsWith@Rect@Foundation@Windows@@QEAA_NV123@@Z
@ stub ?Invert@Matrix3D@Media3D@Media@Xaml@UI@Windows@@QEAAXXZ
@ stub ?ReCreateException@Exception@Platform@@SAPE$AAV12@H@Z
@ stub ?ReferenceEquals@Object@Platform@@SA_NPE$AAV12@0@Z
@ stub ?ReferenceEquals@Object@Platform@@SA_NPE$AAVString@2@0@Z
@ stub ?RegisterFactories@Details@Platform@@YAPE$AAVObject@2@PEAPEAVModuleBase@1WRL@Microsoft@@PEAPEAU__abi_Module@@P6AXXZ@Z
@ stub ?ReleaseInContextImpl@Details@Platform@@YAJPEAUIUnknown@@0@Z
@ stub ?ReleaseTarget@ControlBlock@Details@Platform@@AEAAXXZ
@ stub ?ResolveWeakReference@Details@Platform@@YAPE$AAVObject@2@AEBU_GUID@@PEAPEAU__abi_IUnknown@@@Z
@ stub ?RunApplicationServer@Details@Platform@@YAXPEAPEAVModuleBase@1WRL@Microsoft@@PEAPEAU__abi_Module@@PEB_W@Z
@ stub ?RunServer@Details@Platform@@YAXPEAPEAVModuleBase@1WRL@Microsoft@@PEAPEAU__abi_Module@@PEB_W@Z
@ stub ?TerminateModule@Details@Platform@@YA_NPEAVModuleBase@1WRL@Microsoft@@@Z
@ stub ?ToInt32@IntPtr@Platform@@QEAAHXZ
@ stub ?ToString@Attribute@Metadata@Platform@@QE$AAAPE$AAVString@3@XZ
@ stub ?ToString@Boolean@Platform@@QEAAPE$AAVString@2@XZ
@ stub ?ToString@Delegate@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub ?ToString@Enum@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub ?ToString@Exception@Platform@@UE$AAAPE$AAVString@2@XZ
@ stub ?ToString@Guid@Platform@@QEAAPE$AAVString@2@XZ
@ stub ?ToString@MTAThreadAttribute@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub ?ToString@OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@QE$AAAPE$AAVString@4@XZ
@ stub ?ToString@STAThreadAttribute@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub ?ToString@Type@Platform@@UE$AAAPE$AAVString@2@XZ
@ stub ?ToString@ValueType@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub ?ToString@char16@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@float32@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@float64@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@int16@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@int32@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@int64@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@int8@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@uint16@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@uint32@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@uint64@default@@QEAAPE$AAVString@Platform@@XZ
@ stub ?ToString@uint8@default@@QEAAPE$AAVString@Platform@@XZ
@ stdcall ?UninitializeData@Details@Platform@@YAXH@Z(long) wincorlib.?UninitializeData@Details@Platform@@YAXH@Z
@ stub ?Union@Rect@Foundation@Windows@@QEAAXV123@@Z
@ stub ?Union@Rect@Foundation@Windows@@QEAAXVPoint@23@@Z
@ stub ?WriteLine@Console@Details@Platform@@SAXPE$AAVObject@3@@Z
@ stub ?WriteLine@Console@Details@Platform@@SAXPE$AAVString@3@@Z
@ stub ?WriteLine@Console@Details@Platform@@SAXXZ
@ stub ?__abi_FailFast@@YAXXZ
@ stub ?__abi_ObjectToString@__abi_details@@YAPE$AAVString@Platform@@PE$AAVObject@3@_N@Z
@ stub ?__abi_Resolve@ControlBlock@Details@Platform@@UEAAJAEAVGuid@3@PEAPEAU__abi_IInspectable@@@Z
@ stub ?__abi_WinRTraiseAccessDeniedException@@YAXXZ
@ stub ?__abi_WinRTraiseCOMException@@YAXJ@Z
@ stub ?__abi_WinRTraiseChangedStateException@@YAXXZ
@ stub ?__abi_WinRTraiseClassNotRegisteredException@@YAXXZ
@ stub ?__abi_WinRTraiseDisconnectedException@@YAXXZ
@ stub ?__abi_WinRTraiseFailureException@@YAXXZ
@ stub ?__abi_WinRTraiseInvalidArgumentException@@YAXXZ
@ stub ?__abi_WinRTraiseInvalidCastException@@YAXXZ
@ stub ?__abi_WinRTraiseNotImplementedException@@YAXXZ
@ stub ?__abi_WinRTraiseNullReferenceException@@YAXXZ
@ stub ?__abi_WinRTraiseObjectDisposedException@@YAXXZ
@ stub ?__abi_WinRTraiseOperationCanceledException@@YAXXZ
@ stub ?__abi_WinRTraiseOutOfBoundsException@@YAXXZ
@ stub ?__abi_WinRTraiseOutOfMemoryException@@YAXXZ
@ stub ?__abi_WinRTraiseWrongThreadException@@YAXXZ
@ stub ?__abi_cast_Object_to_String@__abi_details@@YAPE$AAVString@Platform@@_NPE$AAVObject@3@@Z
@ stub ?__abi_cast_String_to_Object@__abi_details@@YAPE$AAVObject@Platform@@PE$AAVString@3@@Z
@ stub ?__abi_make_type_id@@YAPE$AAVType@Platform@@AEBU__abi_type_descriptor@@@Z
@ stub ?__abi_translateCurrentException@@YAJ_N@Z
@ stub ?__getActivationFactoryByHSTRING@@YAJPEAUHSTRING__@@AEAVGuid@Platform@@PEAPEAX@Z
@ stub ?get@Bottom@Rect@Foundation@Windows@@QEAAMXZ
@ stub ?get@BreakOnAllocationId@Heap@Details@Platform@@SAHXZ
@ stub ?get@BreakOnFreeId@Heap@Details@Platform@@SAHXZ
@ stub ?get@CurrentAllocationId@Heap@Details@Platform@@SAHXZ
@ stub ?get@Empty@Rect@Foundation@Windows@@SA?AV234@XZ
@ stub ?get@Empty@Size@Foundation@Windows@@SA?AV234@XZ
@ stub ?get@FullName@Type@Platform@@QE$AAAPE$AAVString@3@XZ
@ stub ?get@HasInverse@Matrix3D@Media3D@Media@Xaml@UI@Windows@@QEAA_NXZ
@ stub ?get@Message@Exception@Platform@@QE$AAAPE$AAVString@3@XZ
@ stub ?get@ObjectCount@Heap@Details@Platform@@SAHXZ
@ stub ?get@Right@Rect@Foundation@Windows@@QEAAMXZ
@ stub ?get@TrackingLevel@Heap@Details@Platform@@SA?AW4HeapAllocationTrackingLevel@34@XZ
@ stub ?set@BreakOnAllocationId@Heap@Details@Platform@@SAXH@Z
@ stub ?set@BreakOnFreeId@Heap@Details@Platform@@SAXH@Z
@ stub ?set@TrackingLevel@Heap@Details@Platform@@SAXW4HeapAllocationTrackingLevel@34@@Z
